name: dart_frog_pizza_shop
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  json_annotation:

dev_dependencies:
  build_runner:
  json_serializable:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
  